<?php

use App\Http\Controllers\Api\Cms\AuthController;
use App\Http\Controllers\Api\Cms\BannerController;
use App\Http\Controllers\Api\Cms\BlogCategoryController;
use App\Http\Controllers\Api\Cms\BlogController;
use App\Http\Controllers\Api\Cms\CarrierController;
use App\Http\Controllers\Api\Cms\Catalog\AttributeController;
use App\Http\Controllers\Api\Cms\Catalog\FilterController;
use App\Http\Controllers\Api\Cms\Catalog\ManufacturerController;
use App\Http\Controllers\Api\Cms\Catalog\OptionController;
use App\Http\Controllers\Api\Cms\CategoryController;
use App\Http\Controllers\Api\Cms\CustomerController;
use App\Http\Controllers\Api\Cms\DistrictController;
use App\Http\Controllers\Api\Cms\FileController;
use App\Http\Controllers\Api\Cms\InformationController;
use App\Http\Controllers\Api\Cms\MenuController;
use App\Http\Controllers\Api\Cms\MenuValueController;
use App\Http\Controllers\Api\Cms\Order\OrderController;
use App\Http\Controllers\Api\Cms\OrderStatusController;
use App\Http\Controllers\Api\Cms\PaymentController;
use App\Http\Controllers\Api\Cms\ProductController;
use App\Http\Controllers\Api\Cms\ResourceController;
use App\Http\Controllers\Api\Cms\SettingController;
use App\Http\Controllers\Api\Cms\StoreReviewController;
use App\Http\Controllers\Api\Cms\System\RoleController;
use App\Http\Controllers\Api\Cms\System\UserGroupController;
use App\Http\Controllers\Api\Cms\SystemController;
use App\Http\Controllers\Api\Cms\UserController;
use App\Http\Controllers\Api\Cms\WardController;
use App\Http\Controllers\Api\Cms\WarehouseController;
use App\Http\Controllers\Api\Cms\ZoneController;
use Illuminate\Support\Facades\Route;

Route::post('login', [AuthController::class, 'login']);
Route::get('system/init', [SystemController::class, 'init']);

Route::middleware('auth:sanctum')->group(function () {
    Route::get('me', [AuthController::class, 'me']);
    Route::post('logout', [AuthController::class, 'logout']);
    Route::get('resource', [ResourceController::class, 'index']);
    Route::post('file/upload', [FileController::class, 'upload']);
    Route::post('file/upload-video', [FileController::class, 'uploadVideo']);
    Route::middleware('cms.permission')->group(function () {
        Route::cmsApiResource('category', CategoryController::class);
        Route::cmsApiResource('filter', FilterController::class);
        Route::cmsApiResource('attribute', AttributeController::class);
        Route::cmsApiResource('option', OptionController::class);
        Route::cmsApiResource('manufacturer', ManufacturerController::class);
        Route::cmsApiResource('banner', BannerController::class);
        Route::cmsApiResource('store-review', StoreReviewController::class);
        Route::post('product/bulk-update', [ProductController::class, 'bulkUpdate']);
        Route::post('product/{id}/approve', [ProductController::class, 'approve']);
        Route::cmsApiResource('product', ProductController::class);
        Route::cmsApiResource('warehouse', WarehouseController::class);
        Route::cmsApiResource('order', OrderController::class);
        Route::cmsApiResource('blog', BlogController::class);
        Route::get('blog-category', [BlogCategoryController::class, 'index']);
        Route::cmsApiResource('menu', MenuController::class);
        Route::get('menu-value', [MenuValueController::class, 'index']);
        Route::get('menu-value/{menuValue}', [MenuValueController::class, 'show']);
        Route::post('menu-value', [MenuValueController::class, 'store']);
        Route::put('menu-value/{menuValue}', [MenuValueController::class, 'update']);
        Route::patch('menu-value/{menuValue}/rename', [MenuValueController::class, 'rename']);
        Route::delete('menu-value/{menuValue}', [MenuValueController::class, 'destroy']);
        Route::post('menu/{menuId}/values/reorder', [MenuValueController::class, 'reorder']);
        Route::post('menu/{menuId}/values/import-category', [MenuValueController::class, 'importCategory']);
        Route::delete('menu/{menuId}/values/categories', [MenuValueController::class, 'deleteCategories']);
        Route::cmsApiResource('information', InformationController::class);
        Route::post('order/preview-total', [OrderController::class, 'previewTotal']);
        Route::get('order-status', [OrderStatusController::class, 'index']);
        Route::get('carrier', [CarrierController::class, 'index']);
        Route::get('payment', [PaymentController::class, 'index']);
        Route::get('zone', [ZoneController::class, 'index']);
        Route::get('district', [DistrictController::class, 'index']);
        Route::get('ward', [WardController::class, 'index']);
        Route::get('role/permissions/registry', [RoleController::class, 'permissionsRegistry']);
        Route::apiResource('role', RoleController::class);
        Route::get('user', [UserController::class, 'index']);
        Route::cmsApiResource('user-group', UserGroupController::class);
        Route::cmsApiResource('user-group', UserGroupController::class);
        Route::get('user/admin-list', [UserController::class, 'adminList']);
        Route::patch('user/{id}/restore', [UserController::class, 'restore']);
        Route::post('user/bulk', [UserController::class, 'bulk']);
        Route::apiResource('user', UserController::class)->except(['index'])->withTrashed();
        Route::patch('customer/{id}/restore', [CustomerController::class, 'restore']);
        Route::post('customer/bulk', [CustomerController::class, 'bulk']);
        Route::apiResource('customer', CustomerController::class)->withTrashed();
        Route::get('setting', [SettingController::class, 'show']);
        Route::put('setting', [SettingController::class, 'update']);
        Route::post('setting/del', [SettingController::class, 'clearCache']);
    });
});
