<?php

namespace App\Data\Output;

use App\Models\Entities\ReviewTag;
use Spatie\LaravelData\Data;

class ReviewTagDTO extends Data
{
    public function __construct(
        public int $id,
        public string $code,
        public string $name,
        public int $usageCount,
        public bool $isAutoGenerated,
    ) {}

    public static function fromModel(ReviewTag $m): self
    {
        $desc = $m->description;
        return new self(
            id:              (int) $m->id,
            code:            (string) $m->code,
            name:            (string) ($desc->name ?? $m->code),
            usageCount:      (int) $m->usage_count,
            isAutoGenerated: (bool) $m->is_auto_generated,
        );
    }
}
